stages:
  - build
  - deploy

build-stg:
  before_script:
    - export REACT_APP_SITE_URL=https://stg-website.com
  image: node:13.14-alpine
  stage: build
  cache:
    paths:
      - build/
  script:
    - npm install
    - npm run build
  only:
    - develop

build-prod:
  before_script:
    - export REACT_APP_SITE_URL=https://prod-website.com
  image: node:13.14-alpine
  stage: build
  cache:
    paths:
      - build/
  script:
    - npm install
    - npm run build
  only:
    - master

deploy-stg:
  image: python:alpine
  stage: deploy
  cache:
    paths:
      - build/
    policy: pull
  script:
    - apk add python3-dev
    - pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync build/ s3://stg-gitlab-ci-react
  only:
    - develop

deploy-prod:
  image: python:alpine
  stage: deploy
  cache:
    paths:
      - build/
    policy: pull
  script:
    - apk add python3-dev
    - pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync build/ s3://prod-gitlab-ci-react
  only:
    - master
